version: 2

updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    reviewers:
      - "sevensa-team"
    assignees:
      - "sevensa-team"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "jest*"
          - "@testing-library/*"

  # Python Poetry dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    reviewers:
      - "sevensa-team"
    assignees:
      - "sevensa-team"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    ignore:
      # Ignore major version updates that might break compatibility
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
    groups:
      langchain:
        patterns:
          - "langchain*"
          - "langgraph"
      fastapi:
        patterns:
          - "fastapi"
          - "uvicorn"
          - "starlette"
      database:
        patterns:
          - "sqlalchemy"
          - "alembic"
          - "psycopg2*"
          - "asyncpg"
      testing:
        patterns:
          - "pytest*"
          - "testcontainers"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    reviewers:
      - "sevensa-team"
    assignees:
      - "sevensa-team"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    reviewers:
      - "sevensa-team"
    assignees:
      - "sevensa-team"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
