apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentguy-api
  namespace: sevensa-rentguy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: NODE_ENV
          value: development
        - name: LOG_LEVEL
          value: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentguy-frontend
  namespace: sevensa-rentguy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
