version: '3.8'

# Dit bestand definieert de Keycloak Identity Provider setup voor Zero-Trust Network Access
# Keycloak dient als centrale authenticatie- en autorisatieserver voor alle services

services:
  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HOSTNAME=auth.sevensa.nl
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/auth
      # Productie-instellingen
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    command: start
    volumes:
      - keycloak-themes:/opt/keycloak/themes
    networks:
      - traefik-net
      - keycloak-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.sevensa.nl`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      # Health check endpoint voor Traefik
      - "traefik.http.routers.keycloak.middlewares=keycloak-retry"
      - "traefik.http.middlewares.keycloak-retry.retry.attempts=5"
      - "traefik.http.middlewares.keycloak-retry.retry.initialinterval=1s"
    depends_on:
      - keycloak-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # PostgreSQL database voor Keycloak
  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
      # Initialisatiescript voor database optimalisatie
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - keycloak-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Keycloak configuratie tool (optioneel, kan worden uitgeschakeld na initiële setup)
  keycloak-config-cli:
    image: quay.io/adorsys/keycloak-config-cli:5.3.1-21.1.1
    container_name: keycloak-config-cli
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=120s
      - IMPORT_PATH=/config
    volumes:
      - ./keycloak-config:/config
    networks:
      - keycloak-net
    depends_on:
      - keycloak
    restart: on-failure

networks:
  traefik-net:
    external: true
  keycloak-net:
    external: true

volumes:
  keycloak-db-data:
    name: keycloak-db-data
  keycloak-themes:
    name: keycloak-themes
