services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    ports: ["80:80"]
    volumes: [ "./nginx.conf:/etc/nginx/conf.d/default.conf:ro" ]
    depends_on: [agency,wpcs,n8n,mcp,installer]
  agency:
    image: python:3.11-slim
    working_dir: /app/agency
    command: bash -lc "pip install -r /app/agency/requirements.txt && uvicorn api.main:app --host 0.0.0.0 --port 8081"
    volumes: [ "./agency:/app/agency", "./core:/app/core" ]
  wpcs:
    image: python:3.11-slim
    working_dir: /app/wpcs
    command: bash -lc "pip install -r /app/wpcs/requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8082"
    volumes: [ "./wpcs:/app/wpcs", "./core:/app/core" ]
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-changeme}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-PLEASE_SET_RANDOM_32_CHARS}
      - N8N_HOST=${N8N_HOST:-agency.sevensa.nl}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-https}
    ports: ["5678:5678"]
    volumes: [ "./n8n/flows:/data/flows" ]
  mcp:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install fastapi uvicorn pyyaml && uvicorn mcp.server:app --host 0.0.0.0 --port 8787"
    volumes: [ "./mcp:/app/mcp", "./core:/app/core", "./mcp/policy:/app/mcp/policy:ro", "/opt/data:/opt/data:ro", "/var/www:/var/www:ro", "/opt/repos/default:/opt/repos/default:ro" ]
    ports: ["8787:8787"]
  redis:
    image: redis:alpine
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    volumes: [ "./grafana/dashboards:/var/lib/grafana/dashboards" ]
  sevensa-scanner:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "python sevensa/scanner/scanner.py"
    volumes: [ "./sevensa:/app/sevensa" ]
    environment:
      - SCAN_INTERVAL=300
      - SEVENSA_STATE=/var/lib/sevensa/state.json
  sevensa-repair:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install pyyaml && python sevensa/repair_agent/repair.py"
    volumes: [ "./sevensa:/app/sevensa", "./core:/app/core" ]
    environment:
      - REPAIR_POLICY=sevensa/repair_agent/repair_policy.yaml
      - SEVENSA_STATE=/var/lib/sevensa/state.json
  installer:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r installer/requirements.txt && uvicorn installer.server:app --host 0.0.0.0 --port 8089"
    volumes: [ "./installer:/app/installer", "./core:/app/core" ]
    ports: ["8089:8089"]
