version: '3.8'

# Dit bestand definieert de HashiCorp Vault setup voor Centralized Secret Management
# Vault dient als centrale opslag voor alle secrets (wachtwoorden, API keys, certificaten)

services:
  # Vault server
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    command: server
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_API_ADDR=https://vault.sevensa.nl:8200
      - VAULT_LOG_LEVEL=info
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/certs:/vault/certs
    ports:
      - "8200:8200"
    networks:
      - traefik-net
      - vault-net
      - rentguy-net
      - psra-net
      - wpcs-net
      - ai-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.sevensa.nl`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
      # OIDC authenticatie middleware
      - "traefik.http.routers.vault.middlewares=vault-auth"
      - "traefik.http.middlewares.vault-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.vault-auth.forwardauth.authResponseHeaders=X-Forwarded-User,X-Forwarded-Email,X-Forwarded-Preferred-Username"
      - "traefik.http.middlewares.vault-auth.forwardauth.trustForwardHeader=true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "https://localhost:8200/v1/sys/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  # Vault configurator - initialiseert en configureert Vault
  vault-configurator:
    image: hashicorp/vault:1.13.3
    container_name: vault-configurator
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_SKIP_VERIFY=true
    volumes:
      - ./vault/scripts:/scripts
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
    networks:
      - vault-net
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # Wacht tot Vault beschikbaar is
      until wget --spider --no-check-certificate https://vault:8200/v1/sys/health 2>/dev/null; do
        echo 'Waiting for Vault to start...'
        sleep 5
      done
      
      # Voer het initialisatiescript uit
      sh /scripts/init-vault.sh
      
      # Blijf draaien om logs te kunnen bekijken
      echo 'Vault configuration completed'
      tail -f /dev/null
      "
    restart: on-failure

networks:
  traefik-net:
    external: true
  vault-net:
    name: vault-net
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.11.0/24
  rentguy-net:
    external: true
  psra-net:
    external: true
  wpcs-net:
    external: true
  ai-net:
    external: true

volumes:
  vault-data:
    name: vault-data
  vault-logs:
    name: vault-logs
