apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sevensa-rentguy

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
  - hpa.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - serviceaccount.yaml
