apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rentguy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sevensa/sevensa-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/overlays/prod/rentguy
  destination:
    server: https://kubernetes.default.svc
    namespace: sevensa-rentguy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
