apiVersion: v1
kind: Secret
metadata:
  name: rentguy-db-credentials
  namespace: sevensa-rentguy
  labels:
    app: rentguy
type: Opaque
stringData:
  url: "postgresql://rentguy:${DB_PASSWORD}@rentguy-db:5432/rentguy"
  username: "rentguy"
  password: "${DB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rentguy-redis-credentials
  namespace: sevensa-rentguy
  labels:
    app: rentguy
type: Opaque
stringData:
  url: "redis://:${REDIS_PASSWORD}@rentguy-redis:6379/0"
  password: "${REDIS_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rentguy-jwt
  namespace: sevensa-rentguy
  labels:
    app: rentguy
type: Opaque
stringData:
  secret: "${JWT_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rentguy-keycloak
  namespace: sevensa-rentguy
  labels:
    app: rentguy
type: Opaque
stringData:
  client_secret: "${KEYCLOAK_CLIENT_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rentguy-openbao
  namespace: sevensa-rentguy
  labels:
    app: rentguy
type: Opaque
stringData:
  role_id: "${OPENBAO_ROLE_ID}"
  secret_id: "${OPENBAO_SECRET_ID}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rentguy-tls
  namespace: sevensa-rentguy
  labels:
    app: rentguy
type: kubernetes.io/tls
data:
  tls.crt: "${TLS_CRT}"
  tls.key: "${TLS_KEY}"
