apiVersion: v1
kind: ServiceAccount
metadata:
  name: rentguy-sa
  namespace: sevensa-rentguy
  labels:
    app: rentguy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rentguy-role
  namespace: sevensa-rentguy
  labels:
    app: rentguy
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rentguy-rolebinding
  namespace: sevensa-rentguy
  labels:
    app: rentguy
subjects:
- kind: ServiceAccount
  name: rentguy-sa
  namespace: sevensa-rentguy
roleRef:
  kind: Role
  name: rentguy-role
  apiGroup: rbac.authorization.k8s.io
