name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "needs-review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the user need?
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].

        Currently, [describe current pain point]...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternative approaches...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend - UI/UX
        - Backend - API
        - Backend - Database
        - Backend - Authentication
        - Backend - Services
        - Infrastructure
        - Documentation
        - Multiple Components
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocking business operations
        - High - Important for business goals
        - Medium - Would improve user experience
        - Low - Nice to have
    validations:
      required: true

  - type: dropdown
    id: user-impact
    attributes:
      label: User Impact
      description: How many users would benefit from this feature?
      options:
        - All users
        - Most users (>50%)
        - Some users (10-50%)
        - Few users (<10%)
        - Admin/Internal only
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, attach mockups, wireframes, or UI designs
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical requirements, dependencies, or constraints?
      placeholder: |
        - Dependencies: [list any dependencies]
        - Performance considerations: [any performance requirements]
        - Security considerations: [any security requirements]
    validations:
      required: false

  - type: input
    id: business-value
    attributes:
      label: Business Value
      description: What is the expected business value or ROI?
      placeholder: e.g., Increase user retention by 20%, Reduce support tickets
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I have considered the impact on existing users
          required: false
