name: Security Vulnerability
description: Report a security vulnerability (please use responsibly)
title: "[SECURITY]: "
labels: ["security", "critical"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report

        **IMPORTANT:** If this is a critical security vulnerability that could be actively exploited,
        please consider reporting it privately to the security team instead of creating a public issue.

        Contact: security@example.com

        For non-critical security improvements or issues already fixed in newer versions,
        please proceed with this form.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Direct Object Reference (IDOR)
        - Security Misconfiguration
        - Sensitive Data Exposure
        - Missing Encryption
        - Insufficient Logging & Monitoring
        - Server-Side Request Forgery (SSRF)
        - Broken Access Control
        - Cryptographic Failure
        - Injection Vulnerability
        - Insecure Deserialization
        - Vulnerable Dependencies
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability (CVSS-based)?
      options:
        - Critical (9.0-10.0) - Immediate action required
        - High (7.0-8.9) - Urgent attention needed
        - Medium (4.0-6.9) - Should be fixed soon
        - Low (0.1-3.9) - Minor issue
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the security vulnerability
      placeholder: Describe the vulnerability in detail...
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which components, endpoints, or systems are affected?
      placeholder: |
        - Component: [name]
        - Version: [version]
        - Endpoints: [list affected endpoints]
    validations:
      required: true

  - type: textarea
    id: attack-scenario
    attributes:
      label: Attack Scenario
      description: How could an attacker exploit this vulnerability?
      placeholder: Describe the attack scenario step by step...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability (be careful not to include active exploits)
      placeholder: |
        1. Navigate to [URL]
        2. Perform [action]
        3. Observe [result]
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept (sanitized if necessary)
      placeholder: |
        ```
        [Provide code or request examples]
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Confidentiality Impact: [None/Low/High]
        - Integrity Impact: [None/Low/High]
        - Availability Impact: [None/Low/High]
        - Scope: [Unchanged/Changed]

        Detailed Impact: [describe]
    validations:
      required: true

  - type: dropdown
    id: exploitability
    attributes:
      label: Exploitability
      description: How easy is it to exploit this vulnerability?
      options:
        - Easy - No special tools or skills required
        - Medium - Requires some technical knowledge
        - Hard - Requires advanced skills or special conditions
        - Very Hard - Extremely difficult to exploit
    validations:
      required: true

  - type: dropdown
    id: public-disclosure
    attributes:
      label: Public Disclosure Status
      description: Has this vulnerability been publicly disclosed?
      options:
        - Not Disclosed - Private report
        - Partially Disclosed - Some information public
        - Fully Disclosed - Publicly known
        - Already Fixed - Fixed in newer versions
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: |
        - Affected: v1.0.0 - v2.3.1
        - Fixed in: v2.3.2 (if applicable)
    validations:
      required: true

  - type: textarea
    id: mitigation-recommendations
    attributes:
      label: Suggested Mitigation/Fix
      description: Do you have recommendations for fixing this vulnerability?
      placeholder: |
        - Short-term mitigation: [describe]
        - Long-term fix: [describe]
        - Code changes: [suggest specific changes]
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant CVEs, security advisories, or documentation
      placeholder: |
        - CVE: [CVE-YYYY-XXXXX]
        - CWE: [CWE-XXX]
        - References: [URLs]
    validations:
      required: false

  - type: input
    id: discovered-by
    attributes:
      label: Discovered By
      description: Who discovered this vulnerability? (for credit in security advisories)
      placeholder: Your name or organization (optional)
    validations:
      required: false

  - type: input
    id: discovery-date
    attributes:
      label: Discovery Date
      description: When was this vulnerability discovered?
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Details about the environment where this was discovered
      placeholder: |
        - Environment: [Production/Staging/Development]
        - Configuration: [relevant configuration details]
        - Dependencies: [relevant dependency versions]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional details, screenshots, logs...
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure Agreement
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I am reporting this vulnerability responsibly
          required: true
        - label: I have not publicly disclosed details that could lead to active exploitation
          required: true
        - label: I will allow reasonable time for a fix before public disclosure
          required: true
        - label: I understand this will be treated as a high-priority security issue
          required: true
