name: ci

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - node-version: '20.15.0'
            experimental: false
          - node-version: '22.x'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: make setup

      - name: Verify (lint, typecheck, unit tests)
        run: make test

      - name: Build
        run: make build

      - name: Generate SBOM
        run: make sbom

      - name: Trivy Scan
        run: make scan

      - name: Upload Security Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: |
            sbom/psra-ltsd-enterprise-v2.cdx.json
            sbom/trivy-report.txt

  codeql:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
