name: Rules-as-Code Gate

on:
  pull_request:
    paths:
      - "psr/**"
      - "tests/golden/**"
      - "scripts/rac_validate.sh"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - "poetry.lock"
  push:
    branches: [main]
    paths:
      - "psr/**"
      - "tests/golden/**"
      - "scripts/rac_validate.sh"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  rac-validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pkg-config libssl-dev

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files

      - name: Run golden tests
        run: |
          poetry run pytest tests/golden
